<?php /* @var $this Zend\View\Renderer\PhpRenderer */ ?>
<?php /* @var $exceptionMessage string */ ?>
<?php /* @var $displayExceptions boolean */ ?>
<?php /* @var $whoops Whoops\Run */ ?>
<?php /* @var $exception Exception */ ?>
<?php /* @var $helpMessage string */ ?>

<?php $this->headTitle('Access denied') ?>

<?php if ($displayExceptions): ?>
	<?php $whoops->handleException($exception) ?>
<?php else: ?>
	<p class="alert alert-danger"><?= $exceptionMessage ?></p>

	<?= $helpMessage ?>
<?php endif ?>
