<?php /* @var $this Zend\View\Renderer\PhpRenderer */ ?>
<?php /* @var $exceptionMessage string */ ?>
<?php /* @var $displayExceptions boolean */ ?>
<?php /* @var $exception Exception */ ?>
<?php /* @var $helpMessage string */ ?>

<?php $this->headTitle('Client error') ?>

<?php if ($displayExceptions): ?>
	<?= $this->render('rdn-exception/error/stack-trace', array('exception' => $exception)) ?>
<?php else: ?>
	<p class="alert alert-danger"><?= $exceptionMessage ?></p>

	<?= $helpMessage ?>
<?php endif ?>
