<?php /* @var $this Zend\View\Renderer\PhpRenderer */ ?>
<?php /* @var $exception Exception */ ?>

<style>
	.stack-trace{
		background-color: #f3f3f3;
		font-family: arial, sans-serif;
	}
	.stack-trace .ex-title{
		background-color: #272727;
		color: #666;
		margin: 0;
		padding: 1em;
	}
	.stack-trace .ex-title span:last-of-type{
		color: #cd3f3f;
	}
	.stack-trace .ex-msg{
		background-color: #272727;
		color: #fff;
		font-size: 2em;
		font-weight: normal;
		margin: 0;
		padding: 0 0.5em 0.5em;
	}
	.stack-trace .hl{
		color: #2f6193;
	}
</style>
<?php do { ?>
	<div class="stack-trace">
		<h3 class="ex-title">
			<span><?= implode('</span> \\ <span>', explode('\\', get_class($exception))) ?></span>
			(<?= $exception->getCode() ?>)
		</h3>
		<h2 class="ex-msg"><?= $this->escapeHtml($exception->getMessage()) ?></h2>

		<ol>
			<li>
				<p><code><?= $exception->getFile() ?>:<?= $exception->getLine() ?></code></p>
			</li>
			<?php foreach ($exception->getTrace() as $frame): ?>
				<li>
					<p>
						<?php if (isset($frame['class'])): ?>
							<span class="hl"><?= $frame['class'] ?></span>
						<?php endif ?>
						<?= $frame['function'] ?>
						<?php if (isset($frame['file'])): ?>
							<br/><code><?= $frame['file'] ?>:<?= $frame['line'] ?></code>
						<?php endif ?>
					</p>
				</li>
			<?php endforeach ?>
		</ol>
	</div>

	<?php $exception = $exception->getPrevious() ?>
<?php } while ($exception != null) ?>
